### ISSUE TITLE
Anyway to make this work for multi-targeted projects and not change the namespace?

### ISSUE THREAD

**Issue by winstonpang** [microsoft/XamlBehaviorsWpf#101]
We currently have a big .NET 4 Framework application, it's going to take us close to 6-12 months to move over to .NET 6.

We've decided to phase it, and by doing so have opted to migrate projects gradually to the new SDK style and then multi-targetting to output both net4* and net-6.0 assemblies.

This is all ok, but sometimes we have WPF components using Behaviors. I mean one way around this for the actual Behavior class is to conditionally compile the using namespace for the behavior classes we create. But the issue is still the usages of it in our XAML code as well, because you can't conditionally compile anything in XAML.

I guess the question is, has anyone done something like what we are doing, and what have you done to get around this?

**Comment by brianlagunas** [comment]
I'm a little confused. The `Microsoft.Xaml.Behaviors.Wpf` Nuget package has binaries for both DNF and .NET 5/6

![image](https://user-images.githubusercontent.com/835562/150230123-768ffbf8-c96b-4802-90f8-4eeea9d8ea4d.png)

This should just work. Prism uses this package and targets `net461;net47;netcoreapp3.1;net5.0-windows`

**Comment by winstonpang** [comment]
Ok so to give a bit more context.

Say you have a WPF class library - Shared.WPF

Shared.WPF contains:

- 30 custom behaviors
- 10 custom controls (xaml files)

Shared.WPF targets net-6.0-windows;net462

Shared.WPF has Microsoft.Xaml.Behaviors.WPF installed

Updating the 30 custom behaviors to the new Microsoft.Xaml.Behaviors namespace as well as updating the 10 custom controls to the new namespace as well.

Everything builds and it's fine. However our project structure has in the vicinity of 70-80 or more projects referencing Shared.WPF. They have not all been converted to multi-targeted projects yet, and it will serve as quite a task to do it all at once due to how we release some of these components out into our product, so it's not just a find all xmlns and replace with the new one.


Originally I had something like this inside the Shared.WPF.csproj

`	<Reference Include="System.Windows.Interactivity">
		<HintPath>..\..\lib\System.Windows.Interactivity.dll</HintPath>
	</Reference>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf " Version="1.1.39" />
	</ItemGroup>`

And inside each of the behaviors:

`#if NETFRAMEWORK
using System.Windows.Interactivity
#endif

#if NETCOREAPP
using Microsoft.Xaml.Behaviors;
#endif`

10 controls have their xmlns updated to 

` xmlns:i="http://schemas.microsoft.com/xaml/behaviors"`

But you can probably see what issue this would have, the 10 controls that make use of the behaviors compile with errors because when it tries to compile for net462 the xmlnns doesn't exist.

**Comment by brianlagunas** [comment]
XAML does not support ifdef. Either remove the need for xaml namespaces in your behaviors by adding them in code, or you'll need to update all your projects
