### ISSUE TITLE
XamlBehaviorsWpf breaks WPFSharpGlobalizer functionality

### ISSUE THREAD

**Issue by Daimonion1980** [microsoft/XamlBehaviorsWpf#105]
**Describe the bug**
First I'm using [WPFSharp.Globalizer](https://github.com/rhyous/WPFSharp.Globalizer) in my application to get the localization done. 
Second I was in the need to invoke a comand on a datagrid and therefore i installed XamlBehaviorsWpf as nuget Package in my application. 
But when using the interaction.trigger from this package the DesignTime functionality from WPFSharp.Globalizer got broken and text elements were not displayed anymore. 

The compiled code works as intended. It is only a DesignTime bug but, an annoying bug.

I'm aware of the point that this issue also can be a WPFsharp.Globalizer but because it first came up when using XamlBehaviorWpf I'm starting my questioning at this place. 

**To Reproduce**
1. Adding both nuget packages in latest version to a project
2. Using globalizer to manage a text element on a button or anyone else where it's needed
3. Adding a interaction.trigger functionality to any element which can work with the feature provided by XamlBehaviorWpf. To show you this in an example I used a button tag, not the datagrid in my main application. 
4. The text elements got broken in design view, after recompile (Build Solution)
5. When disabling the behavior feature text elements will be restored after recompile the code.

**Expected behavior**
Both packages should be able to be implemented side by side. 
I see no compatibility issues between these two packages

**Screenshots**
Working DesignTime view with WPFSharp.Globalizer and XamlBehaviorWpf deactivated:
![image](https://user-images.githubusercontent.com/12880413/157844435-535b65d0-d745-4f0b-b8b8-b392f5fa1863.png)

Broken DesignTime view WPFSharp.Globalizer and XamlBehaviorWpf activated:
![image](https://user-images.githubusercontent.com/12880413/157844830-7d8962e2-f650-4bdf-9ebd-972f766dae89.png)

**Desktop (please complete the following information):**
IDE = Visual Studio 2022

**Reproduction Link**
I got these issue first on my application and reproduced it on the sample application from WPFsharp.Globalizer which is available in the zip-file attached:
[WPFSharp.Globalizer_BehaviorExample.zip](https://github.com/microsoft/XamlBehaviorsWpf/files/8230944/WPFSharp.Globalizer_BehaviorExample.zip)

The example is found in MVVM Example in PersonView.xaml
![image](https://user-images.githubusercontent.com/12880413/157844997-ca4b9caa-8df2-491e-b358-6f77ce87330c.png)

**Comment by brianlagunas** [comment]
Hey @Daimonion1980 I looked at this for awhile and could easily duplicate it using the app you provided. However, I couldn't find a cause in the Behaviors codebase. I also noticed that this designer issue only happens to the `globalizer:GlobalizedResource`. So I am not sure if they have code in that class that is causing an issue, or if it's a Visual Studio designer issue.

I would recommend reporting this to the globalizer repo, or maybe even the Visual Studio team.

The good news is that the app still runs, so you're not blocked, just annoyed. Good luck.
