### ISSUE TITLE
Reversibility of property changes for triggers

### ISSUE THREAD

**Issue by user98392** [microsoft/XamlBehaviorsWpf#106]
The problem is that we burdened to duplicate our triggers in order to restore state of properties.
For example, data triggers from WPF can do that.

**Comment by brianlagunas** [comment]
There is not enough information in your issue to understand the problem you are having. Please provide more detail and a sample app to reproduce the issue.

**Comment by brianlagunas** [comment]
Generally speaking, a DataTrigger will put properties back to their previous value when the specified condition is no longer true.

However, the same is not true for actions. There's no way for the trigger to know what action would "undo" the effect of the triggered action, assuming that there is even such an action.

For what you are trying to do, I would recommend using a Style Trigger instead. Remove the `Button.Effect` from your Button in MainWindow.xaml and update your ButtonStyle to use a trigger instead.

Something like this:

```xml
<Setter Property="Button.Effect">
    <Setter.Value>
        <DropShadowEffect ShadowDepth="0" Color="#36096D" />
    </Setter.Value>
</Setter>

<Style.Resources>
    <Storyboard x:Key="PlayBackgroundShadeStoryboard">
        <DoubleAnimation Storyboard.TargetProperty="(Button.Effect).BlurRadius" To="20" Duration="0:0:0.2"/>
    </Storyboard>
    <Storyboard x:Key="StopBackgroundShadeStoryboard">
        <DoubleAnimation Storyboard.TargetProperty="(Button.Effect).BlurRadius" To="0" Duration="0:0:0.2"/>
    </Storyboard>
</Style.Resources>

<Style.Triggers>
    <Trigger Property="IsMouseOver" Value="True">
        <Trigger.EnterActions>
            <BeginStoryboard Storyboard="{StaticResource PlayBackgroundShadeStoryboard}" />
        </Trigger.EnterActions>
        <Trigger.ExitActions>
            <BeginStoryboard Storyboard="{StaticResource StopBackgroundShadeStoryboard}" />
        </Trigger.ExitActions>
    </Trigger>
</Style.Triggers>
```
