### ISSUE TITLE
Remove reference to Microsoft.Xaml.Behaviors.Design.dll

### ISSUE THREAD

**Issue by bplatypus** [microsoft/XamlBehaviorsWpf#108]
**Describe the bug**
Using this package adds a reference to 'Microsoft.Xaml.Behaviors.Design.dll' in the csproj. And due to this, I have the following build error:
`Cannot resolve dependency to assembly 'Microsoft.Windows.Design.Extensibility, Version=4.3.1.0`

I know I can add it trough the 'Add Resource / Extensions' but I don't want to because it's deprecated. Apparently the 'new' version for this is [https://www.nuget.org/packages/Microsoft.VisualStudio.DesignTools.Extensibility] (https://www.nuget.org/packages/Microsoft.VisualStudio.DesignTools.Extensibility)

So can this package not depend on the new Microsoft.VisualStudio.DesignTools.Extensibility?

**Expected behavior**
Don't depend on Microsoft.Windows.Design.Extensibility

**Comment by nikola-nignite** [comment]
By the way, build will also fail in CI environments where instead of VS only Build Tools are used. Build Tools don't seem to contain `Microsoft.Windows.Design.Extensibility.dll` so it would have to be committed to source control as well.

**Comment by brianlagunas** [comment]
No response.
