### ISSUE TITLE
How are releases tracked?

### ISSUE THREAD

**Issue by DaveInCaz** [microsoft/XamlBehaviorsWpf#109]
On Nuget I can see that there have been several version updates in the last 1-2 years:
![image](https://user-images.githubusercontent.com/18285074/172934091-4ae79a9f-5a0d-4b3a-aacc-cfffb933977c.png)

but in the [releases section ](https://github.com/microsoft/XamlBehaviorsWpf/releases)here it doesn't show anything newer than 1.1.19. (Neither in releases nor tags).

How can we track changes in the formal release? I'd like to see what the changes have been (ideally in the form of release notes but a list of closed issues would be great too). But I haven't been able to find anything on github so far... but maybe I'm not looking in the right place.

Thanks

**Comment by DaveInCaz** [comment]
@brianlagunas Do you mean to just compare the dates of the commits to the dates on Nuget? Not sure how else to find the correspondance.

Thanks

**Comment by brianlagunas** [comment]
Yes, that’s what I mean.

**Comment by mgoertz-msft** [comment]
@DaveInCaz  I'm sorry, we apparently forgot to create the releases for the later nuget packages. I have gone back, tagged the corresponding commits and created the releases as well.

FYI, you can see description for each nuget version of the package by switching over to the README tab:
![image](https://user-images.githubusercontent.com/14282894/173096170-57a7c459-8fcc-48b1-a116-41a0d7bcb513.png)
