### ISSUE TITLE
Microsoft.Xaml.Behaviors.Design.dll exception on project load

### ISSUE THREAD

**Issue by surgutsky** [microsoft/XamlBehaviorsWpf#112]
There's a strange problem that appeared on my laptop.
I have latest VS 2019 Community edition installed.
Latest Microsoft.Xaml.Behaviors.Wpf 1.1.39 is used in couple of projects of my solution.
And on solution load it shows the following error in Output:

There was an exception when loading the design time assembly 'C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\16.0_0162c6fa\Designer\ShadowCache\kwsekyd1.ygs\4oy3amb3.jln\Design\Microsoft.Xaml.Behaviors.Design.dll':
The type initializer for 'Targets' threw an exception.

I tried clearing the ShadowCache, rebuild, reboot, everything, but still the problem appears.
And I encounter subsequent WPF styles problem with VS XAML Designer.
But it could be related to that problem with Microsoft.Xaml.Behaviors.Design.dll, so I need to fix it first somehow.

Please help :-)
Thank you!

**Comment by brianlagunas** [comment]
This is going to be very difficult to address without the ability to reproduce it. Can anyone else reproduce this issue?

**Comment by surgutsky** [comment]
BTW, the runtime works perfectly, no errors.

**Comment by surgutsky** [comment]
I found where was the problem.
It was related to Visual Studio 2019 settings.
Our projects are compiled for x64 mode and this was the reason why it didn't work.
By default VS 2019 uses x86 WPF XAML Designer and you should go to Tools->Options, Environment->Preview Features.
And turn on New WPF XAML Designer.
This successfully fixed the problem.
