### ISSUE TITLE
Brokeen Link

### ISSUE THREAD

**Issue by SezMe** [microsoft/XamlBehaviorsWpf#113]
The "Clone this wiki locally" link is broken.

**Comment by brianlagunas** [comment]
Which link are you talking about? Can you provide specific details on where this broken link is?

**Comment by SezMe** [comment]
Sorry, I was not specific.  On the Wiki page, in the lower right of the page there is the "Clone this wiki locally"i link.   That is the one that is broken.

**Comment by brianlagunas** [comment]
The link is not broken and works as expected.
