### ISSUE TITLE
How to use NavigationMenuAction,is there any sample for this?

### ISSUE THREAD

**Issue by zmrbak** [microsoft/XamlBehaviorsWpf#114]
Is there any sample for  NavigationMenuAction?

I found some examples in old SketchFlow project, but it did not work  in wpf with .net 6.

**Comment by brianlagunas** [comment]
From my recollection, this action is a left over from the old SketchFlow support. As the idea of a "screen" is unique to a SketchFlow project, only SketchFlow projects have behaviors for navigation between screens.

I have never personally used any of the Prototyping Actions, so if anyone has any other insight it would be appreciated. I am closing this as there have been no other responses from the community and I am unable to provide any further information.
