### ISSUE TITLE
IntelliSense support?

### ISSUE THREAD

**Issue by CodingOctocat** [microsoft/XamlBehaviorsWpf#116]
It is possible to provide intellisense when I type in `EventName` and `PropertyName`?

```XAML
<behaviors:Interaction.Triggers>
                <behaviors:EventTrigger EventName="💡MouseLeftButtonDown">
                    <behaviors:ChangePropertyAction PropertyName="💡Fill">
                        <behaviors:ChangePropertyAction.Value>
                            <SolidColorBrush Color="Red" />
                        </behaviors:ChangePropertyAction.Value>
                    </behaviors:ChangePropertyAction>
                </behaviors:EventTrigger>
            </behaviors:Interaction.Triggers>
```

**Comment by brianlagunas** [comment]
I have researched this quite a bit and have been unable to find any extension points that would allow us to implement this behavior.

If anyone else has knowledge in this space, please feel free to add to the conversation.  Until then, I am closing this as "won't implement".

**Comment by CodingOctocat** [comment]
Resharp may be able to do it,  it will probably require a lot of complex code.

Here is a simple but not very elegant solution:
1. use reflection to get event names and writable property names of all built-in controls of WPF
2. generate them as enums
3. use Markup extensions

The end use case looks like this:

```XAML
<i:Interaction.Triggers>
    <i:EventTrigger EventName="{ix: Events.Button = Click}">
        <i:ChangePropertyAction PropertyName="{ix: Properties.Button = Fill}">
                <i:ChangePropertyAction.Value>
                        <SolidColorBrush Color="Red" />
                </i:ChangePropertyAction.Value>
        </i:ChangePropertyAction>
  </i:EventTrigger>
</i:Interaction.Triggers>
```

**Comment by brianlagunas** [comment]
I thought I found a solution to this but turns out it doesn't work in the newest VS designer. Apparently, it would only work in the old .NET Framework based designer.  I have reached out to my contacts at Microsoft that own the VS designer to see if they have any information on how to achieve this.

**Comment by mgoertz-msft** [comment]
@brianlagunas Why don't you add me to that mail thread (mgoertz @ microsoft.com)? I own the XAML IntelliSense and have always been involved in our Extensibility discussions anyway. I'm curious to see your proposal.

**Comment by brianlagunas** [comment]
Oh nice! Didn't know that. 

Historically, I would use TypeConverters and implement the `GetStandardValues` method to provide a list of available values in intellisense. However, it seems this no longer works in the latest VS designer.  I just tested my WPF product as well (I manage the Infragistics WPF Controls) and it seems all our properties that used TypeConverters to provide values to the property grid no longer work.

So, my assumption based off my testing is that the new VS Designer no longer respects the `GetStandardValues` method.

I'll add you to my email thread with Olia.
