### ISSUE TITLE
InvokeCommandAction - add additional properties for more MVVM scenarios

### ISSUE THREAD

**Issue by brianlagunas** [Microsoft/XamlBehaviorsWpf#12]
I would like to suggest we add some additional properties to the InvokeCommandAction to make it more useful in WPF applications using the MVVM pattern.

Suggested properties:
- EventArgsParameterPath - a path to extract a property value from the EventArgs instance to pass to the ICommand as the command parameter.
- EventArgsConverter - a converter to convert the event args to a more friendly type meant for ViewModel consumption.
- EventArgsConverterParameter - an argument passed as parameter to the EventArgsConverter that can be used to make more complex decisions.

Thoughts?

**Comment by Gergilcan** [comment]
I think it is a good idea but instead of eventargsparameterPath i would like to have a DisplayMemberPath in order to be able to select a property value fron the event args OR the result of the converter(post-evaluated)

**Comment by brianlagunas** [comment]
DisplayMemberPath has a different meaning in WPF and does not apply to this concept. If anything, ValueMemberPath would be closer, however it is still not clear exactly what that name does in the context of the InvokeCommandAction behavior.  However, I am not against an `EventArgsMemberPath` or ``EventArgsValueMemberPath`.  Also, applying the parameter path tot he return result of a converter doesn't make sense. You are explicitly opting into using a converter, no need to add additional complexity to the result of that converter.

**Comment by nigel-sampson** [comment]
Agree for the converter params, am always a little worried about Path / reflection based properties. But can see how it would be useful. As long as all three play well together. Would ParameterPath affect the value passed to the converter?

**Comment by brianlagunas** [comment]
No. The parameters path takes precedent over the EventArgsConverter. If the EventArgsParametrPath is not set, then the EventArgsConverter would be used (only if PassEventArgsToCommand was set to true).

The order of operations is as follow:
- CommandParameter
- EventArgsParameterPath
- EventArgsConverter (is PassEventArgsToCommand = true)

**Comment by brianlagunas** [comment]
I was almost thinking that `PassEventArgsToCommand` would only control if the actual EventArgs are passed as a parameter since that is a major MVVM "no-no". If an EventArgsConverter was found then use it regardless of the `PassEventArgsToCommand` property.

**Comment by brianlagunas** [comment]
Fixed with PR #14

**Comment by usernamedd** [comment]
why isnot there a sample about PassEventArgsToCommand
