### ISSUE TITLE
Should we remove the use of MSBuild.Sdk.Extras?

### ISSUE THREAD

**Issue by brianlagunas** [microsoft/XamlBehaviorsWpf#126]
If I remember correctly, the `MSBuild.Sdk.Extras` was used because at the time the `Microsoft.NET.Sdk` was lacking functionality. I do not believe that is the case today.

Is there any reason we should keep using the `MSBuild.Sdk.Extras`?

If not, I would recommend we drop the use of the  `MSBuild.Sdk.Extras` and move to using the official `Microsoft.NET.Sdk`.

Thoughts?

**Comment by mgoertz-msft** [comment]
Now that we no longer support .NET Core 3.1 and 5.0 we probably don't need this anymore.
