### ISSUE TITLE
Add .netcore3.0 build Target

### ISSUE THREAD

**Issue by dotMorten** [microsoft/XamlBehaviorsWpf#13]
Please add an explicit `netcoreapp3.0` Target to ensure compatibility.

I've done this with WPF class libs before, so feel free to assign to me and I'll submit a PR.

**Comment by brianlagunas** [comment]
Done! Knock it out.

**Comment by dotMorten** [comment]
One small complication: I can add this easily after merging #17. However this would require you to install .NET Core 3.0 Preview to be able to compile the solution. Are we OK with this?
Alternatively we could make it a build-switch to turn on for testing purposes.

**Comment by dotMorten** [comment]
One more complication: MSTest doesn't support running threads in STA, so most tests fail on .NET Core. I logged issue: https://github.com/Microsoft/vstest/issues/1865

**Comment by brianlagunas** [comment]
I'm okay with requiring .NET Core 3 preview to be installed to build from source. I'm all about moving the project forward.  I think the workaround for the .NET Core3 tests are fine too.

**Comment by dotMorten** [comment]
I'm curious if this'll affect the CI builds though. I know @onovotny was struggling with that.

**Comment by dotMorten** [comment]
> I think the workaround for the .NET Core3 tests are fine too.

It'll be temporary anyway. Working on a PR to fix this in MSTest (they already acknowledged this needs to be addressed)

**Comment by brianlagunas** [comment]
Well, we don't have CI builds yet sooo… lol

It's a simple fix. We would basically create a small script to download and install the latest Core 3 SDK on the build server. I do this with Prism and it works fine.

**Comment by dotMorten** [comment]
Sounds good. I'll prepare the PR if/when the csproj changes gets merged

**Comment by onovotny** [comment]
Here's all you need to get .NET Core on it, whatever version you want:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/azure-pipelines.yml#L29-L31

**Comment by onovotny** [comment]
And this line will make the machine use the latest version that matches regardless of being a preview msbuild or not: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/global.json#L3

**Comment by onovotny** [comment]
If you move the tests to xUnit, it supports STA tests ;)

**Comment by dotMorten** [comment]
@onovotny Changing TestClass to STATestClass is a much smaller change than moving to xunit :-p

**Comment by brianlagunas** [comment]
@onovotny I know, that's exactly what I did for Prism :)

**Comment by dotMorten** [comment]
I'm getting second thoughts here.... do we really need to do this? You can use the assembly as-is in .NETCore 3.0. We just need to test for it and address issues like the LaunchUri action, but until we really need to `#if-def` code specific for each platform, is this strictly necessary?

**Comment by brianlagunas** [comment]
Nothing is forcing us to add .NET Core 3 support now. We could put this off until later as it gets closer to RTM.  Maybe we wait until the requests for .NET Core 3 support increase.

**Comment by brianlagunas** [comment]
I also don't think it hurts anything. I also have selfish motivations since Prism supports .NET Core 3 and I just changed from System.Windows.Intractivity to use the new Behvaiors package :)

**Comment by dotMorten** [comment]
It was more in the interest of the "If it ain't broke" mantra - especially considering things are still preview. We could make it a build-condition until .NET Core is final?

**Comment by onovotny** [comment]
If you want to get fancy, `TargetFrameworks` can be a variable set in a directory props file`. Then it can be overridden by a build script.

**Comment by brianlagunas** [comment]
I don't think we're ready to get that fancy yet :)

**Comment by onovotny** [comment]
It can be switched to xUnit, which doesn't suffer that problem ;)

**Comment by dotMorten** [comment]
@onovotny That's completely irrelevant to this PR. You should consider logging an issue with a list of all the amazing things this would provide and then submit a PR for it :-p

**Comment by prajaybasu** [comment]
Any updates on this?

**Comment by brianlagunas** [comment]
We are waiting for DevOps to be put in place before accepting anymore PRs.  We must be able to validate the build and have the ability to release the product.

**Comment by prajaybasu** [comment]
> We are waiting for DevOps to be put in place before accepting anymore PRs.  We must be able to validate the build and have the ability to release the product.

Ah ok. Everything works fine for me right now, but a preview .NET Core 3.0 build would make some warnings disappear when working with WPF on .NET Core.

**Comment by Lakritzator** [comment]
Today I was looking at the current state of dotnet core 3.0 support for all the projects I use directly and indirectly. There still are many which cause warnings, they seem to work fine but still. I was making a list of packaged which I would help out, if possible, to solve the support. This package arrived on my list :grin: 

Is there anything I can do to help?
Is there still an issue with the "strong naming"? You should be able to skip this for dotnet core.
And the waiting for DevOps, is this something that needs to be done at the microsoft side or are you talking about someone spending time with making it work on Azure DevOps?

**Comment by dotMorten** [comment]
This is mainly waiting for 3.0 to finalize.
You can just ignore the warning for now.

**Comment by Dirkster99** [comment]
Hi,

NetCore 3 is in the stabilization phase and should be good to go - is there any special reason this build target is not being added here?

I am having a build dependency and cannot continue to convert my applications to NetCore 3 just because of a missing behavior ...

**Comment by brianlagunas** [comment]
@Dirkster99 I know this project has seemed to have hit a brick wall, but the efforts should b picking up soon. We are just waiting for the key players to get some bandwidth to manage this.

**Comment by virzak** [comment]
@Dirkster99 I had the same [issue](https://github.com/microsoft/XamlBehaviorsWpf/issues/36) a few months back..

Looks like this is [nuget package](https://www.nuget.org/packages/Nuctech.Xaml.Behaviors.Wpf/) implements most of the latest functionality.

**Comment by Dirkster99** [comment]
@virzak the nuget package Nuctech.Xaml.Behaviors.Wpf.1.0.2 supports only Net4.5 so its not really helpfull for usage with NetCore 3 as its producing the same warning as this project does (unless  I am missing something?):

> ...\MLib\source\Components\MWindowLib\MWindowLib.csproj : warning NU1701: Package 'Nuctech.Xaml.Behaviors.Wpf 1.0.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

**Comment by virzak** [comment]
@Dirkster99 no, you're correct. My bad.

**Comment by mgoertz-msft** [comment]
FYI, the official NuGet package may produce a warning but it is actually fully compatible with .NET Core 3 and doesn't use any unsupported APIs.

AFAIK @brianlagunas uses it himself for the .NET Core 3 version of Prism.

**Comment by Dirkster99** [comment]
@mgoertz-msft Now I am completely confused. The last and only version 1.0.01 of the [NuGet package](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) appears to be 9 months old.

...and, yet, you are saying it already supports NetCore 3?

**Comment by dotMorten** [comment]
Yes that's what he's saying and he's correct. You can use .net framework assemblies in .net core as long as those assemblies doesn't hit unsupported APIs. You get a warning that it might happen in your build, but otherwise you're ok.

**Comment by weltkante** [comment]
@dotMorten it doesn't work though? dotnet/wpf#1935 shows a compiler error when trying to reference it

**Comment by tom-englert** [comment]
Now that NetCore 3.0.100 is officially released, there should be no obstacles left to release this!

**Comment by chris-ray** [comment]
+1. .NET Core 3 is production. Enterprise folks like me are converting our projects. This warning is ... annoying... even if not a problem.

**Comment by dotMorten** [comment]
@chris-ray just add the warning to the NoWarn list. Hardly a showstopper

**Comment by Dirkster99** [comment]
I am still not getting over the error stage as @weltkante [has reported before](https://github.com/microsoft/XamlBehaviorsWpf/issues/13#issuecomment-535839733) and I have seen no answer to this... what am I missing?

Maybe someone who has all the details could give a small list of detailed instructions of how to use this library in a .netcore3 scenario despite the fact that its usage generates a compilation error (@dotMorten What NoWarn list are you refering to (in VS?)). Otherwise, I have to admit this is **still** a showstopper for me :-(

Thanks

**Comment by Lakritzator** [comment]
@Dirkster99 @weltkante that is curious, as for me the example project in https://github.com/dotnet/wpf/issues/1935 works just fine. What I did notice is that the dotnet --info shows that the version used is a release candidate. I've seen quite a lot of weird issues, mostly because those versions need a specfic nuget.config, so I would advice you to make sure you have the release version of dotnet core 3.0 installed!

On top of that, just in case make sure you have .net framework Target packs which match the package. What version of the .NET Framework do you have? Do you have a full blown Visual Studio installation?

**Comment by weltkante** [comment]
I'm not the OP of dotnet/wpf#1935 - I was just linking it up since the issue on the WPF repo got closed without resolution and the discussion here looked like it should just work. Just wanted to point out it doesn't work for everyone. Maybe @Dirkster99 can give more information on the scenario.

**Comment by Lakritzator** [comment]
@weltkante I know you are not.

So you don't have an issue yourself or do you? I'm a bit confused...
What is important about that other issue, if that I DO get an error when I just download the .zip, extract and run dotnet build. But I always "automatically" remove bin / obj directories as they contain binaries and garbage, which could influence the build in a bad way, and in this case they do. So delete the obj directory, and things should work.

**Comment by Dirkster99** [comment]
The scenario I am looking at is really not that exotic - I am using VS 2019 Community with .NetCore 3 and I was getting an error message when I used the NuGet from this project in a NetCore WPF project. I just updated VS today with netcore 3.0.100 and tried it now again by creating a simple WPF netcore project and it seems to behave this time as described above:
![Untitled](https://user-images.githubusercontent.com/2129700/66348957-0615da00-e958-11e9-9cd8-9e511032190a.png)

I see a warning 1701 and the warning is by default suppressed but still visible in the output window. Strange I tried it yesterday with VS 2019 Community Preview and was still getting an error where everyone here was talking about a warning - OK, now that I get the warning I'll try to convert the app now for the third time :-) and keep fingers crossed that it works now as prescribed - but I still don't know what was meant with the 'NoWarn List' ...

**Comment by weltkante** [comment]
> but I still don't know what was meant with the 'NoWarn List' ...

Its the "suppress warnings" list in your screenshot, in the csproj file the field storing this list is called `NoWarn`

**Comment by dotMorten** [comment]
All done!
https://dev.azure.com/dotnet/XamlBehaviorsWpf/_build/results?buildId=22944&view=artifacts

**Comment by chris-ray** [comment]
@dotMorten Cool! When will it be released to nuget?

**Comment by dotMorten** [comment]
@chris-ray I'm not the maintainer of this project, so I have no say in that.

**Comment by brianlagunas** [comment]
@chris-ray we are targeting a Nov 4th release.

**Comment by virzak** [comment]
@brianlagunas Any chance of a preview release before that time?

**Comment by brianlagunas** [comment]
The link to the build artifact (nuget package) has already been provided by @dotMorten.

**Comment by DVaughan** [comment]
NuGet package [1.0.30](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/1.0.30) is now available.

**Comment by brianlagunas** [comment]
@DVaughan that was much faster than we originally thought 😄 Great job!
