### ISSUE TITLE
InvokeCommandAction for IsVisibleChanged Command not work

### ISSUE THREAD

**Issue by CodingOctocat** [microsoft/XamlBehaviorsWpf#137]
I use `MVVM Toolkit` and  `XamlBehaviorsWpf`, They worked fine until I started using the `IsVisibleChanged` event, and I found that the event handler `UserControl_IsVisibleChanged` was called correctly (no doubt), but the `FooCommand` was not called.

To add, this should not be a problem with my code, as other event commands can be called (e.g. Loaded)

View:

```XAML
<UserControl IsVisibleChanged="UserControl_IsVisibleChanged">
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="IsVisibleChanged">
            <i:InvokeCommandAction Command="{Binding FooCommand}" />
        </i:EventTrigger>
    </i:Interaction.Triggers>
</<UserControl>
```

Vm:

```CS
[RelayCommand]
private void Foo()
{
    // not called.
}
```

Code-Behind:

```CS
private void UserControl_IsVisibleChanged(object sender, System.Windows.DependencyPropertyChangedEventArgs e)
{
    // normal called.
}
```
**Sample:**

[Issue137Sample.zip](https://github.com/microsoft/XamlBehaviorsWpf/files/11729725/Issue137Sample.zip)

**Comment by CodingOctocat** [comment]
@brianlagunas Sorry, I forgot about the issue template requirement, now I added the sample.

[Issue137Sample.zip](https://github.com/microsoft/XamlBehaviorsWpf/files/11729725/Issue137Sample.zip)

![image](https://github.com/microsoft/XamlBehaviorsWpf/assets/7220248/39119890-50f3-4a4f-bf53-89405d08031e)

**Comment by brianlagunas** [comment]
Thanks for the sample. The reason this is happening is because the `IsVisibileChanged` event is not the correct event type for the built-in `EventTrigger`.

The `IsVisibleChnaged` event is actually a `DependencyPropertyChangedEventHandler` delegate, and does not have an `EventArgs` object, but rather a struct of type `DependencyPropertyChangedEventArgs`.

If you want to support this type of event, you'll need to provide a custom implementation of the event trigger.  Here is an example of a very simple and incomplete approach you may take.

```
public class DependencyPropertyChangedEventTrigger : Microsoft.Xaml.Behaviors.EventTrigger
{
    protected override void OnSourceChanged(object oldSource, object newSource)
    {
        RegisterEvent(newSource, GetEventName());
    }

    private void RegisterEvent(object obj, string eventName)
    {
        Type targetType = obj.GetType();
        EventInfo eventInfo = targetType.GetEvent(eventName);
        var eventHandlerMethodInfo = typeof(DependencyPropertyChangedEventTrigger).GetMethod("OnEventImpl", BindingFlags.NonPublic | BindingFlags.Instance);
        eventInfo.AddEventHandler(obj, Delegate.CreateDelegate(eventInfo.EventHandlerType, this, eventHandlerMethodInfo));
    }

    private void OnEventImpl(object sender, DependencyPropertyChangedEventArgs eventArgs)
    {
        //todo: handle your event args and pass them as a proper EventArgs based class
        this.OnEvent(new EventArgs());
    }
}
```

```html
<local:DependencyPropertyChangedEventTrigger EventName="IsVisibleChanged">
     <i:InvokeCommandAction Command="{Binding BorderIsVisibleChangedCommand}" />
</local:DependencyPropertyChangedEventTrigger>
```

This should get you pointed in the right direction.
