### ISSUE TITLE
New Release with .NET 6

### ISSUE THREAD

**Issue by jimwinquist** [microsoft/XamlBehaviorsWpf#141]
I'd like to be able to use the nuget package with the recent .NET 6 revisions. 

Is there a plan to publish a new released nuget pkg with the .NET 6 updates?

**Comment by mgoertz-msft** [comment]
@jimwinquist Yes, there is. We just ran into a few unexpected issues with our build/publishing pipelines that are taking quite a bit longer to get resolved than we anticipated.

**Comment by jimwinquist** [comment]
Thanks for the update @mgoertz-msft. Is there a rough ETA on when you think it will get resolved?

**Comment by echoix** [comment]
i.e. before or after the .NET 8 release this fall?

**Comment by mgoertz-msft** [comment]
Should be before.

**Comment by mgoertz-msft** [comment]
@jimwinquist and @echoix,

Latest release has been published and is available on nuget.org:
- https://github.com/microsoft/XamlBehaviorsWpf/releases/tag/v1.1.75
- https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/1.1.75
