### ISSUE TITLE
Microsoft.VisualStudio.DesignTools.Extensibility not found

### ISSUE THREAD

**Issue by BMa-BS** [microsoft/XamlBehaviorsWpf#142]
When using the newest version 1.1.75, I get a compiler error that the depdendency Microsoft.VisualStudio.DesignTools.Extensibility is not found. When reverting back to version 1.1.39 it compiles fine.

**Comment by mgoertz-msft** [comment]
Thanks, that shouldn't happen. We'll look into it...

**Comment by mgoertz-msft** [comment]
@BMa-BS It builds and runs just fine for me in a blank .NET 8 WPF app where I added a simple change property behavior:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.75" />
  </ItemGroup>

</Project>
```

```xaml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp2"
        xmlns:b="http://schemas.microsoft.com/xaml/behaviors"
        x:Class="WpfApp2.MainWindow"
        mc:Ignorable="d"
        Title="MainWindow"
        Height="450"
        Width="800">
    <Grid>
        <Button x:Name="button"
                Content="Button"
                HorizontalAlignment="Left"
                Margin="173,97,0,0"
                VerticalAlignment="Top">
            <b:Interaction.Triggers>
                <b:EventTrigger EventName="Click">
                    <b:ChangePropertyAction PropertyName="Background">
                        <b:ChangePropertyAction.Value>
                            <SolidColorBrush Color="#FFA53434" />
                        </b:ChangePropertyAction.Value>
                    </b:ChangePropertyAction>
                </b:EventTrigger>
            </b:Interaction.Triggers>
        </Button>

    </Grid>
</Window>
```

What does your project look like?

**Comment by BMa-BS** [comment]
I am using a legacy style .NET Framework 4.8 Class Library project with Visual Studio 2019.

**Comment by mgoertz-msft** [comment]
Thanks! That repros for me as well in VS 2022 and I see what the issue is. The new version includes support for the new design tools extensibility model in VS 2022. SDK style projects handle this automatically but legacy framework projects do not. The new design tools assembly needs to be explicitly removed in the nuget install script that's included in the package. Currently, that script only removes the design assembly. We will need to update that script and publish a new package.

Thank you for bringing this to our attention!

**Comment by LordMartron94** [comment]
I also have this issue currently.

Occurs with the latest version, it's a blank project created in Jetbrains Rider.
![image](https://github.com/microsoft/XamlBehaviorsWpf/assets/85250199/32658057-670f-4e68-b745-eec635482404)

![image](https://github.com/microsoft/XamlBehaviorsWpf/assets/85250199/5fe67df2-23f6-4539-81dd-ff64f2f591b0)

Nothing in the project yet and I can confirm it is this package, because when I remove it, my app builds fine.
Regardless, I need this package to work as Caliburn.Micro depends on it.

**Comment by LordMartron94** [comment]
> I also have this issue currently.
> 
> Occurs with the latest version, it's a blank project created in Jetbrains Rider. ![image](https://private-user-images.githubusercontent.com/85250199/305674651-32658057-670f-4e68-b745-eec635482404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTE4NTcsIm5iZiI6MTcwODIxMTU1NywicGF0aCI6Ii84NTI1MDE5OS8zMDU2NzQ2NTEtMzI2NTgwNTctNjcwZi00ZTY4LWI3NDUtZWVjNjM1NDgyNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIzMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYTRiZTVhNWZhMjAwYWNiNWMyODM0NjliYWRmMjQ5MjgwZDE1M2FmYjNjOWZhYTViMWMxODUwMDYwZDJlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WMMx1mxp_FFikWEgyykXMZahPQu2qe2EXBiWDYgzNHU)
> 
> ![image](https://private-user-images.githubusercontent.com/85250199/305674665-5fe67df2-23f6-4539-81dd-ff64f2f591b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTE4NTcsIm5iZiI6MTcwODIxMTU1NywicGF0aCI6Ii84NTI1MDE5OS8zMDU2NzQ2NjUtNWZlNjdkZjItMjNmNi00NTM5LTgxZGQtZmY2NGYyZjU5MWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIzMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNDdhYzQ5YTAzNjQxM2MzNTQ3MTI0MzMxZGM1NjNmOWFjZTlkNDhkYjFkNGViYWQwNTY3MDZkZjVlOTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6yTjH_oBWV8iBSzNoz8zap06Aa0XQDOfsNVTTljxdY)
> 
> Nothing in the project yet and I can confirm it is this package, because when I remove it, my app builds fine. Regardless, I need this package to work as Caliburn.Micro depends on it.

Nevermind, I am dumb. It's been a while since I programmed in C#, I don't know why I chose .NET Framework instead of .NET itself. 🤦‍♂️
