### ISSUE TITLE
`TriggerBase<T>` doesn't implement `CloneCurrentValueCore`, so `Clone()` is shallow.

### ISSUE THREAD

**Issue by Nintynuts** [microsoft/XamlBehaviorsWpf#146]
**Describe the bug**
When using an attached property to add behaviours or triggers to a style (because the style instance can't be shared) the `Clone()` method on `Freezable` is documented to indicate it's a deep copy, however when doing using it `Actions` is empty. This is because [`Clone`'s common logic](https://referencesource.microsoft.com/#WindowsBase/Base/System/Windows/Freezable.cs,2230e37fe2d04b68) only copies non-read-only dependency properties (which excludes `Actions` since it's a collection).

It's probable that other read-only collection properties on other triggers and behaviours also need this fix.

It would be nice if the attached properties to copy triggers and behaviours from a style were included in this package.

**To Reproduce**
1. Create or install a package including an attached property to apply triggers from a style ([for example](https://github.com/tom-englert/TomsToolbox/blob/master/src/TomsToolbox.Wpf/StyleBindings.cs))
2. Add a trigger to a style using this attached property, with an action
3. Execute the trigger
4. The actions will not happen, because they weren't cloned

**Expected behavior**
The actions should be cloned and executed when triggered.

**Desktop:**
 - Version with bug: 1.1.77
 - Last known working version: none

**Comment by brianlagunas** [comment]
I am not seeing how this is an issue with the WPF Behaviors, but rather how the WPF framework works in general. Thee are no mechanisms in this project that handles the copying of actions/triggers. What is your suggested change in order to support this?

**Comment by Nintynuts** [comment]
The mechanism to copy the actions/triggers is `Freezable.Clone` which `TriggerBase<T>` inherits. I think this can be fixed by implementing `CloneCurrentValueCore` on the `TriggerBase<T>` class, which is there to be overridden and isn't. You're right that this project alone doesn't support copying them in a useful way, but to make them work with styles there are lots of projects (including the one I referenced) which implement an attached property to copy them onto instances, and it doesn't work because the implementation doesn't fulfil the `Clone` contract properly.

**Comment by Nintynuts** [comment]
Also please re-open, this isn't resolved. I'm not sure why you don't see it, but it definitely is an issue with WPF Behaviours.

**Comment by brianlagunas** [comment]
This isn't a bug. It's a feature request. The use-case needs to be more clearly defined or demonstrated. A focused sample would help with this. Based on my current understanding of this request, I'm not confident this is something that would be added.
