### ISSUE TITLE
Setup a CI build

### ISSUE THREAD

**Issue by brianlagunas** [microsoft/XamlBehaviorsWpf#15]
We need to setup a CI build that will run all tests for submitted PRs. We should also publish any CI builds to a separate feed such as MyGet so developers can test the latest feature to provide feedback.

**Comment by onovotny** [comment]
I'll do it.

**Comment by onovotny** [comment]
Is this project in the .NET Foundation?

**Comment by brianlagunas** [comment]
@onovotny No, it's not. Yes, it should be.

**Comment by onovotny** [comment]
Okay...I'll set it up in the dotnet DevOps account, for now while we get the paperwork done. I don't see why it would not be, but I'll verify with Jon.

**Comment by onovotny** [comment]
@brianlagunas can you assign this to me please?

**Comment by brianlagunas** [comment]
@onovotny I tried, it won't let me

![image](https://user-images.githubusercontent.com/835562/49817483-9205a800-fd2d-11e8-9e30-9c4a9427cf89.png)

**Comment by mgoertz-msft** [comment]
@onovotny I invited you to be a collaborator. Once you accept we should be able to assign this to you.

**Comment by onovotny** [comment]
Can someone make me an admin on this repo, at least temporarily? I need it for setting the build as it needs to configure webhooks.

**Comment by mgoertz-msft** [comment]
We will need to discuss the real ownership of this repo at some point but for now probably all [collaborators](https://github.com/Microsoft/XamlBehaviorsWpf/settings/collaboration).

**Comment by onovotny** [comment]
@mgoertz-msft  Okay, all the collaborators and you are admins on the project here: https://dev.azure.com/dotnet/XamlBehaviorsWpf

**Comment by SuperJMN** [comment]
I have seen that there are no builds in the pipeline. Also, the NuGet package in NuGet.org is outdated :(

**Comment by onovotny** [comment]
There's an open PR for this here https://github.com/microsoft/XamlBehaviorsWpf/pull/25
