### ISSUE TITLE
Publish the private key

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/XamlBehaviorsWpf#16]
You should not be using a private key for strong name signing an open source project. It causes all sorts of problems, like you can't just build and run the unit tests, because you hit strong name assembly mismatch.
See doc here: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

> If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.

**Comment by PedroLamas** [comment]
Fully agree, but then again I thought that [this](https://github.com/Microsoft/XamlBehaviorsWpf/blob/master/src/Microsoft.Xaml.Behaviors/FinalPublicKey.snk) was the final private key...

**Comment by dotMorten** [comment]
@MovGP0 That doesn't work from within VS
@PedroLamas from what I can tell it's only the public key (which is why delay sign is turned on)

**Comment by dotMorten** [comment]
Summary of discussion on this:

> Microsoft is not going to release their private key. Instead create a new key that doesn't require signature, and use that. Do this as quick as possible before too many are using this package. Probably also unless the current package up there.

**Comment by dotMorten** [comment]
Our Lord has spoken:
![image](https://user-images.githubusercontent.com/1378165/49815936-b8254b00-fd21-11e8-8df1-6fe46a06696c.png)

**Comment by PedroLamas** [comment]
Done and dusted! 🎉
