### ISSUE TITLE
Associating TextBlock with Checkbox

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/XamlBehaviorsWpf#161]
Or any other _label-esque_ control, with a target other control. In this case, yes, I am wanting `<TextBlock/>` to `<Checkbox/>` click behavior. When the source WPF control is clicked, the target WPF control should receive focus. As I understand it, there is currently no property that says target other control, in WPF, and _attached behaviors_ is the way to go about doing this? Is it supported at all in the current versions of _XamlBehaviorsWpf_?

**Comment by brianlagunas** [comment]
There are no built-in behavior to accomplish this. You will need to implement this behavior yourself.

**Comment by mwpowellhtx** [comment]
Unpacking that a bit, and just to clarify to be clear, no native way to do that? And nothing offered by way of this package? Thanks...
