### ISSUE TITLE
Keytriggers with modifier invoke the action of the keytrigger with the same key and modifier set to None

### ISSUE THREAD

**Issue by salvatorefrancostats** [microsoft/XamlBehaviorsWpf#162]
**Describe the bug**
Keytriggers with modifier invoke the action of the keytrigger with the same key and modifier set to none

**To Reproduce**
1. Create a WPF Application
2. Create MainWindow
3. Add a keytrigger with Key="Up"
4. Add an InvokeCommandAction and bind Command1
5. Add a keytrigger with Key="Up" and Modifiers="Shift"
6. Add an InvokeCommandAction and bind Command2
7. Add breakpoints on both Command1 and Command2
8. Run the application
9. Press Shift+Up on the keyboard
10. Both commands will be fired

**Expected behavior**
Only Command2 will be fired

**Screenshots**
![Xaml Behaviors KeyTrigger Issue](https://github.com/microsoft/XamlBehaviorsWpf/assets/126460481/1871c680-202d-4b4a-bd63-e5fa19d1ecb2)

**Desktop (please complete the following information):**
 - Version with bug: 1.1.75 - 1.1.79
 - Last known working version: 1.1.39

**Reproduction Link**
https://github.com/microsoft/XamlBehaviorsWpf/blob/ca52233144a8969c96c1e911483830a9b3c1d43a/src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs#L77

This check allow keytrigger with modifiers set to none to invoke action also if there is a specific keytrigger for the pressed keys

**Comment by gianlucacuccostatsperform** [comment]
@brianlagunas did you had a chance to check this issue ? we might help to fix?

**Comment by brianlagunas** [comment]
No, I haven't even looked at this yet. My day job has been keeping me extremely busy.

I'm not sure if this is by design, or an oversight in the original implementation.

**Comment by brianlagunas** [comment]
Looking at the history, that fix was added to address issue #77 .

If you have time, a PR would be great. We added tests for the original fix, so as long as those tests don't break, we should be okay. Also, we will need test for any additional changes in that area of the code. It would have been nice to have a test for this scenario so we could have seen the behavior change.

**Comment by gianlucacuccostatsperform** [comment]
@brianlagunas we found those 2 different behavior can't be used at the same time, modifiers can't be used as modifier and as key at same time, we have produce the following pr to keep both behavior and define witch one to apply with a flag UseModifiersAsKeys https://github.com/microsoft/XamlBehaviorsWpf/pull/166/commits/b724af2c16cb30813f318077e23f9aac6781e947

**Comment by brianlagunas** [comment]
@gianlucacuccostatsperform I just submitted a PR for this fix.

**Comment by gianlucacuccostatsperform** [comment]
@brianlagunas thanks for your time and your effort, i tested and it do perfectly work!
