### ISSUE TITLE
KeyTrigger doesn't invoke the command using "ALT" Modifier Key

### ISSUE THREAD

**Issue by salvatorefrancostats** [microsoft/XamlBehaviorsWpf#175]
**Describe the bug**
Keytriggers with modifier "ALT" doesn't invoke the command

**To Reproduce**

1. Create a WPF Application
2. Create MainWindow
3. Add a keytrigger with Key="Up" and Modifiers="Alt"
4. Add an InvokeCommandAction and bind Command1
5. Add breakpoints on Command1
6. Run the application
7. Press Alt+Up on the keyboard

**Current behavior**
Command1 won't be fired
**Expected behavior**
Command1 will be fired

**Screenshots**
![image](https://github.com/user-attachments/assets/80ee6ac9-9b81-43a0-bc4c-9e263b0c3122)

**Desktop (please complete the following information):**
- Version with bug: 1.1.122

**Comment by brianlagunas** [comment]
Please create a simple reproduction app.

**Comment by salvatorefrancostats** [comment]
Hi,
here is a very simple WPF App, using ALT+ArrowDown the command won't be triggered, if you will change it using CTRL as a modifier it will work.

Hope it helps[
[WpfApp1.zip](https://github.com/user-attachments/files/16725722/WpfApp1.zip)
](url)

**Comment by brianlagunas** [comment]
It appears that WPF is seeing the Alt key as the System key AND the Modifier key, so the Down key is never registered. This should be an easy fix.
