### ISSUE TITLE
Consider using Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by dotMorten** [microsoft/XamlBehaviorsWpf#18]
Currently nuget package gets versioned based on timestamps. Consider using Nerdbank.Gitversioning instead. See PR review comment https://github.com/Microsoft/XamlBehaviorsWpf/pull/17#pullrequestreview-183719716

**Comment by onovotny** [comment]
I have this in #25

**Comment by brianlagunas** [comment]
Versioning is solved as we just published a new release.
