### ISSUE TITLE
Add missing repo documents

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/XamlBehaviorsWpf#19]
See this page: https://github.com/Microsoft/XamlBehaviorsWpf/community
![image](https://user-images.githubusercontent.com/1378165/49827655-af8f3d80-fd3e-11e8-9adb-232a3c751ed8.png)

Need to add:
 - [ ] Code of conduct
 - [x] Contributing guidelines
 - [x] Issue template
 - [x] Pull Request template

**Comment by brianlagunas** [comment]
Done! The Code of Conduct is listed on the Readme with a link, so I didn't add the actual .md file for it.
