### ISSUE TITLE
Behaviors SDK installed and WPF behaviors NuGet package added to project

### ISSUE THREAD

**Issue by branh** [microsoft/XamlBehaviorsWpf#2]
## Details about Problem
If a user has already installed the Blend for Visual Studio SDK for .NET and adds the Microsoft.Xaml.Behaviors.Wpf NuGet package to a project, two versions of each behavior will be available.

## Use Case
When WPF Xaml behaviors are available for a project from both the Microsoft.Xaml.Behaviors.Wpf NuGet package and the Blend for Visual Studio SDK for .NET installed on a machine, the asset pane will only show the version of behaviors from the NuGet package.

The behaviors from the NuGet package have different namespaces from behaviors in the Blend for Visual Studio SDK for .NET. Any existing references to the behaviors from the Blend for Visual Studio SDK for .NET will still work and use the old behaviors. Updating to the behaviors from the NuGet package will be as simple as updating the namespace in most cases.

## Detailed Repro Steps so we can see the problem
1. Install the Blend for Visual Studio SDK for .NET component.
2. Open or create a WPF project.
3. Add the Microsoft.Xaml.Behaviors.Wpf NuGet package.
4. Open a XAML page and observe the Behaviors tab of the Assets pane.

**Comment by Zolomon** [comment]
I have the opposite problem, none of the assets are shown once `step 3` is finished.

**Comment by brianlagunas** [comment]
I'm closing this because this would be more of a tooling issue than anything we can do in this repo.  Also, it doesn't seem to be an issue that is impacting anyone on a scale that causes concern.
