### ISSUE TITLE
Update EditorConfig

### ISSUE THREAD

**Issue by brianlagunas** [microsoft/XamlBehaviorsWpf#23]
**Is your feature request related to a problem? Please describe.**
The current editorconfig rules are implementing coding standards that I do not agree with.

**Describe the solution you'd like**
I would like to open a dialog about which rules we should update to the editorconfig file to alig the coding standards more inline with modern development practices.

**Describe alternatives you've considered**
Some examples of items I would like to change:
- private variables should start with an underscore `_`
- else/else if statements should be on a newline (currently the are inline)

Here is the editorconfig we used for the UWP behvaiors:
https://github.com/Microsoft/XamlBehaviors/blob/master/src/BehaviorsSDKManaged/.editorconfig

We could just use that if we want.

Thoughts?

**Comment by nigel-sampson** [comment]
We can break this down into two lists.

1. Places where the existing codebase differs from the editorconfig e.g. else statements
2. Places where we don't agree with the current rules e.g. private variables.

**Comment by brianlagunas** [comment]
I'm closing this as any code formatting changes that need to be made, can be made on a case-by-case basis, and by the people who are active in the code base. Though, we'll want to make sure we try to align with other MS repos coding styles.
