### ISSUE TITLE
Suggest to change XmlnsPrefix casing to lowercase.

### ISSUE THREAD

**Issue by xxMUROxx** [Microsoft/XamlBehaviorsWpf#29]
I suggest to change the XmlnsPrefix from **Interactions** to **interactions** since other libraries uses lower case to and ReSharper suggests me to change the casing to lowercase.

> Name 'Interactions' does not match rule 'Namespace alias'. Suggested name is 'interactions'.

PR referenced: #28

**Comment by brianlagunas** [comment]
I would actually prefer to see a shorter prefix such as just `i` instead of a full `interactions`.

Actually, I think it's strange that a `Microsoft.Xaml.Behaviors` namespace maps to an `interactions` prefix. Doesn't it make more sense to map to a `behaviors` prefix or simply a `b`?

**Comment by xxMUROxx** [comment]
I like Shorter prefixes too, should i change the PR to that one so that the cange can, later, be merged?

**Comment by PedroLamas** [comment]
You have 3x "ok" here, I think it's safe to go ahead with this change.

**Comment by brianlagunas** [comment]
I also would prefer to change this to just `b`
