### ISSUE TITLE
ConditionBehavior - Question of Use & NuGet not in sync with what's in Github,

### ISSUE THREAD

**Issue by smeddows** [microsoft/XamlBehaviorsWpf#33]
I have a scenario where a `ConditionBehavior` would seem like a right fit but I can't figure out how to use the code.   The Condition example doesn't use this Behavior.   Can you throw one or two together real quick, please?

**Comment by smeddows** [comment]
I figured out what I needed to do to get the condition to execute:

`<i:Interaction.Triggers>
        <i:EventTrigger EventName="Closing">
            <i:Interaction.Behaviors>
                <i:ConditionBehavior>
                    <i:ConditionalExpression>
                        <i:ComparisonCondition LeftOperand="{Binding IsDirty}" RightOperand="true" Operator="Equal" />
                    </i:ConditionalExpression>
                </i:ConditionBehavior>
            </i:Interaction.Behaviors>
            <i:InvokeCommandAction Command="{Binding QueryToSaveClaimCommand}" />
        </i:EventTrigger>
    </i:Interaction.Triggers>`

This works fine and the RelayCommand from the MVVMLight Toolkit will execute.  However, I'm not getting the `EventArgs` passed in as a parameter.  Even when I cast the parameter as `object`, I get a `null`.

'public ICommand QueryToSaveClaimCommand =>RelayCommand<object>(async e => {});`

`e` is always `null`.  What am I doing wrong?

**Comment by smeddows** [comment]
Again, I think I solved my own problem, just here to document it for everyone.   The version on NuGet is NOT the same one as on here.

Is there a plan to keep what is published here in sync with what is on NuGet?   I'd prefer to have the package in my project vs the project.

Thanks
Scott

**Comment by adrianhara** [comment]
@brianlagunas could you please publish a new version on NuGet to fix this?

**Comment by brianlagunas** [comment]
@adrianhara unfortunately, the entire publishing process belongs to Microsoft. I do not have the ability to publish releases to Nuget :(

**Comment by adrianhara** [comment]
@brianlagunas I see. What would be the best way to trigger someone to publish it, do you know?

**Comment by brianlagunas** [comment]
A new version has been published to NuGet.
