### ISSUE TITLE
Microsoft.Xaml.Interations.Core - Erro

### ISSUE THREAD

**Issue by jonatassiqueiraaraujo** [microsoft/XamlBehaviorsWpf#34]
Ola, ao tentar criar um botão para navegar entre duas páginas, o botão não funciona na versão do Visual Studio 2019.  

<Grid>
        <AppBarButton x:Name="appBarButton" Icon="Accept" Label="AppBarButton">
            <Custom:Interaction.Behaviors>
                <Custom1:EventTriggerBehavior EventName="Click">
                    <Custom1:NavigateToPageAction TargetPage="Video01"/>
                </Custom1:EventTriggerBehavior>
            </Custom:Interaction.Behaviors>
        </AppBarButton>
    </Grid>

![NavigateToPageAction](https://user-images.githubusercontent.com/50753903/57955898-849cad00-78cd-11e9-8b16-d99b1eaf40c7.JPG)

**Comment by PedroLamas** [comment]
Este problema não está no repositório correcto (este repositório é para WPF, o projecto na imagem é UWP que está [aqui](https://github.com/microsoft/XamlBehaviors)), pelo que vou fechar.

(Nota: aconselho que este tipo de problemas sejam descritos sempre em Inglês para assim haver mais pessoas a poderem responder!)
