### ISSUE TITLE
Event properties are missing from the nuget package

### ISSUE THREAD

**Issue by virzak** [microsoft/XamlBehaviorsWpf#36]
Event properties are missing from the nuget package

https://github.com/microsoft/XamlBehaviorsWpf/blob/294a4bc12ac671eed0de68bc7722dd68d627f516/src/Microsoft.Xaml.Behaviors/InvokeCommandAction.cs#L22-L24

That means that MVVM Light's [implementation ](https://github.com/lbugnion/mvvmlight/blob/4cbf77ca6fbe91f83cece8fbf288b166c54202c5/GalaSoft.MvvmLight/GalaSoft.MvvmLight.Platform%20(NET45)/Command/EventToCommand.cs#L296)is the only option for us at this time:

**Comment by brianlagunas** [comment]
That's because those new properties have not been released via NuGet yet. They will be available with the next RTM release.
