### ISSUE TITLE
No support for .NET Framework 4.0

### ISSUE THREAD

**Issue by redcurry** [microsoft/XamlBehaviorsWpf#52]
**Description**
Adding Microsoft.Xaml.Behaviors.Wpf from NuGet to a WPF .NET Framework 4.0 application fails with the error:

> Could not install package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The NuGet description does not show any specific dependencies to a .NET Framework version. If the .NET Framework 4.0 is not truly supported, this should be made clear somewhere.

**Expected behavior**
NuGet package is properly referenced and added to the "References" list of the project. If .NET Framework 4.0 is not meant to be supported, this should be made clear in the NuGet description.

**Comment by brianlagunas** [comment]
I would think the fact that it will not install into a .NET 4.0 project would be clear enough.

**Comment by redcurry** [comment]
Many NuGet packages are clear as to which .NET Framework versions they support, and it's nice to know before attempting to install it. Many NuGet packages continue to support the .NET Framework 4.0 (and earlier) even though official support ended.

**Comment by brianlagunas** [comment]
Can you provide some examples of exactly what you're looking for?

**Comment by redcurry** [comment]
If you browse the packages NLog, DryIoc.dll, and MvvmLightLibs, you can clearly see which .NET Framework versions they support.

**Comment by brianlagunas** [comment]
Links are more helpful than descriptions.

**Comment by redcurry** [comment]
Sorry, they're not links. I'm browsing these from Visual Studio (when you right-click on a project and select "Manage NuGet Packages...").

**Comment by brianlagunas** [comment]
Screenshots?

**Comment by redcurry** [comment]
Actually, NLog's NuGet page specifies which versions it supports: https://www.nuget.org/packages/NLog/4.6.7

**Comment by brianlagunas** [comment]
I'm not sure the nuget package description is where supported environment info should go. However, adding something to the read me might be helpful. If you'd like,  you can put together a PR for review.

**Comment by redcurry** [comment]
DryIoc.dll doesn't specify the supported framework versions in its description, but under Dependencies, it does show several .NET Framework versions:

![image](https://user-images.githubusercontent.com/1739707/66728631-0872ab00-ee14-11e9-97e7-e4cb159eca14.png)

**Comment by brianlagunas** [comment]
Fixed with latest update:
![image](https://user-images.githubusercontent.com/835562/66770688-78654d80-ee75-11e9-9fcf-9f7490efb241.png)
