### ISSUE TITLE
nuget package contains debug build

### ISSUE THREAD

**Issue by vslynko** [microsoft/XamlBehaviorsWpf#55]
[Nuget Package](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) v 1.0.30
contains debug build with assembly version number 1.0.0.0 which is lower than previous version 1.0.1.0 of package version 1.0.1

v 1.0.1
![image](https://user-images.githubusercontent.com/12891283/66900458-23544380-effd-11e9-9456-824e51cc2cf7.png)
v 1.0.30
![image](https://user-images.githubusercontent.com/12891283/66900574-5dbde080-effd-11e9-849c-00a1fbb338d2.png)

**Comment by DVaughan** [comment]
The AssemblyVersion attribute was removed from AssemblyInfo.cs last year by @dotMorten. Morten, do you know why?

Regarding the debug assemblies, I'm investigating.

**Comment by DVaughan** [comment]
I'm updating version.json to use "version": "1.1" to ensure the version number is greater than the previous.

**Comment by DVaughan** [comment]
The new package has been published:
[package version 1.1.3](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/1.1.3)

I verified that it contains release assemblies with version 1.1.0.0.

**Comment by vslynko** [comment]
looks good now

**Comment by DVaughan** [comment]
Thanks for letting me know, Vadim.
