### ISSUE TITLE
Add 1.1 release to GitHub

### ISSUE THREAD

**Issue by gtaylor1981** [microsoft/XamlBehaviorsWpf#58]
Can the latest 1.1 release be added to GitHub too please?
Perhaps with a short changelog?

**Comment by DVaughan** [comment]
[1.1](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) is published on GitHub. 
Or am I missing something? (I do that a lot)

**Comment by brianlagunas** [comment]
Thanks for the reminder. We forgot to create and tag a release.  It is now available. I will be updating the change log shortly

https://github.com/microsoft/XamlBehaviorsWpf/releases/tag/v1.1.3
