### ISSUE TITLE
Set behaviors globally

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/XamlBehaviorsWpf#63]
## Feature request

Enable setting behaviors via a style or in any other way that it can be applied globally on a control.

### Description

I'm trying to set [a behavior](https://stackoverflow.com/a/59203094/75500) so that it applies on all `TextBox`es in my application via a global style.

I've tried the following:
```xaml
<Style TargetType="TextBox">
  <Setter Property="b:Interaction.Behaviors">
    <Setter.Value>
      <local:DataAnnotationsBehavior/>
    </Setter.Value>
  </Setter>
</Style>
```
But I get this error:
>XDG0041: The property "Behaviors" is not a DependencyProperty. To be used in markup, non-attached properties must be exposed on the target type with an accessible instance property "Behaviors". For attached properties, the declaring type must provide static "GetBehaviors"  and "SetBehaviors" methods.

My suggestion is that you make a `DependencyProperty` out of the `Behaviors` property or enable applying it globally somehow.

**Comment by brianlagunas** [comment]
It's important to understand that behaviors and triggers are associated with a specific object instance.  You cannot use the same instance of a behavior for multiple/different object instances. When you define your behavior to a specific object (in XAML or code), it forces this one-to-one relationship. However, when you try to set a behavior in a style, the style can be re-used for all objects it applies to and this will throw exceptions in the base behavior classes.

**Comment by weitzhandler** [comment]
Thanks for your response.
Ended up using an attached property instead.
