### ISSUE TITLE
'Interaction.Triggers' does not exist 

### ISSUE THREAD

**Issue by rmorgan001** [microsoft/XamlBehaviorsWpf#65]
**Describe the bug**
received this error after upgrading to 1.1.19 in Microsoft Visual Studio Community 2019
Version 16.4.3

microsoft.xaml.behaviors 'Interaction.Triggers' does not exist in XML namespace 'http://schemas.microsoft.com/xaml/behaviors'

**To Reproduce**
I loaded all previous packages and up to 1.1.3 and they work.

**Expected behavior**
no build errors

**Desktop (please complete the following information):**
 - Version with bug: Windows 10 home 1903

<Window x:Class="GS.ChartViewer.MainWindowV"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" TextElement.FontSize="14" ResizeMode="CanResizeWithGrip"  WindowStyle="None" 
        xmlns:properties="clr-namespace:GS.ChartViewer.Properties"
        xmlns:controls="clr-namespace:GS.ChartViewer.Controls"
        xmlns:md="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
        xmlns:local="clr-namespace:GS.ChartViewer"
        xmlns:Interactions="http://schemas.microsoft.com/xaml/behaviors"
        xmlns:shared="clr-namespace:GS.Shared;assembly=GS.Shared"
        xmlns:enums="clr-namespace:LiveCharts.Geared;assembly=LiveCharts.Geared"
        xmlns:helpers="clr-namespace:GS.ChartViewer.Helpers"
...
                    <Interactions:Interaction.Triggers>
                        <Interactions:EventTrigger EventName="PreviewMouseLeftButtonUp">
                            <Interactions:InvokeCommandAction Command="{Binding ClickPulsesSeriesCmd}" CommandParameter="{Binding ElementName=ListView1, Path=SelectedItem}"/>
                        </Interactions:EventTrigger>
                    </Interactions:Interaction.Triggers>

**Comment by brianlagunas** [comment]
I'm sorry, but you did not provide a sample that reproduces your issue. Please submit a reproduction app and I will reopen to investigate.
