### ISSUE TITLE
Trigger EnterActions & ExitActions

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [microsoft/XamlBehaviorsWpf#66]
Please, implement actions in triggers when the condition is NOT fulfilled, so that you would not have to write 2 separate triggers in Xaml. Like the ones implemented in WPF DataTrigger.EnterActions and DataTrigger.ExitActions. It would be very convenient. Thanks.

**Comment by ApokalmiX** [comment]
I had the same question, I'm looking to have the same behavior as Style.Triggers so that the initial values of the controls are put back in place when the condition is no longer met. I couldn't find any other solution than to use two triggers with inverted conditions.

**Comment by brianlagunas** [comment]
This feature request has been open for many years with no meaningful activity.

I am closing this as "won't implement"
