### ISSUE TITLE
TranslateZoomRotateBehavior set ConstrainToParentBounds="True" useless

### ISSUE THREAD

**Issue by peter-wwj** [microsoft/XamlBehaviorsWpf#71]
<Canvas Width="800" Height="500" Margin="49,39,108,339">
                <Rectangle Width="80" Height="80" Fill="DeepPink">
                    <Behaviors_i:Interaction.Behaviors>
                        <Behaviors_i:TranslateZoomRotateBehavior TranslateFriction="0.8" RotationalFriction="0.8" MinimumScale="0.4" MaximumScale="2" ConstrainToParentBounds="True" />
                    </Behaviors_i:Interaction.Behaviors>
                </Rectangle>
            </Canvas>

TranslateZoomRotateBehavior set ConstrainToParentBounds="True" useless，and Changed event useless too, my project use vs2017+wpf+.net 4.5+Microsoft.Xaml.Behaviors.Wpf v1.1.19

**Comment by brianlagunas** [comment]
Thank you for providing your opinion on the ConstrainToParentBounds property.
