### ISSUE TITLE
Event Binding Markup Extension

### ISSUE THREAD

**Issue by las-nsc** [microsoft/XamlBehaviorsWpf#72]
**Is your feature request related to a problem? Please describe.**
Attached behaviours work fine but are a little cumbersome and long-winded compared to bindings.

**Describe the solution you'd like**
Like with `{Binding ...}` markup on properties, allow `{EventBinding ...}` on events which offers the same mechanisms as event triggers (`InvokeCommandAction` with `EventArgsConverter` in particular). So rather than:
```xaml
<MyControl>
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="MyEvent">
            <i:InvokeCommandAction Command="{Binding MyCommand}" EventArgsConverter="{StaticResource MyConverter}"/>
        </i:EventTrigger>
    </i:Interaction.Triggers>
</MyControl>
```

```xaml
<MyControl MyEvent="{i:EventBinding MyCommand, Converter={StaticResource MyConverter}}"/>
```

**Describe alternatives you've considered**
I have seen 2 or 3 implementations of this idea in nuget, but they don't work as nicely as the mechanism used by behaviours (either too simple or over-complicated).

**Additional context**

**Comment by brianlagunas** [comment]
Thank you for the idea, but markup extensions fall outside of the scope of the Behaviors project.
