### ISSUE TITLE
Does Not Compile in Visual Studio 2019? error 	Unable to locate repository containing directory ..XamlBehaviorsWpf-master\src\Microsoft.Xaml.Behaviors'.	Microsoft.Xaml.Behaviors

### ISSUE THREAD

**Issue by stevensrf11** [microsoft/XamlBehaviorsWpf#74]
I download the source code.
When I tried to rebuild the soluton I Code the following compile errors:
Severity	Code	Description	Project	File	Line	Suppression State
![Untitled](https://user-images.githubusercontent.com/22349374/91229620-c979db00-e6ef-11ea-907f-a5f823ec40eb.png)

Error		Unable to locate repository containing directory 'C:\Prism 7_2\XamlBehaviorsWpf-master\src\Microsoft.Xaml.Behaviors'.	Microsoft.Xaml.Behaviors	C:\Users\spaceradar\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20

Am I missing something like some kind of restore

**Comment by PedroLamas** [comment]
I believe this is due to the fact you downloaded the code instead of doing a `git clone`.

If you do a `git clone` it should just work!

**Comment by stevensrf11** [comment]
I downloaded a zip file.

The directory exist , but when compiling the vs saids the directory does not exist

 
 

Sent: Wednesday, August 26, 2020 at 8:22 AM

**Comment by PedroLamas** [comment]
I know you download a zip (I assumed that when I saw "XamlBehaviorsWpf-master" on the path), what I'm saying is that that is the reason why it failed to build!

Please clone the repo locally with `git clone` instead of downloading it and try again.

**Comment by stevensrf11** [comment]
I did a clone and got the same compile errors.

I even choose let Visual Studio open option and got the same compile errors

 
 

Sent: Wednesday, August 26, 2020 at 9:22 AM

**Comment by PedroLamas** [comment]
Ok, seems there's a versioning issue with Microsoft.VisualStudio.DesignTools.* references, that will have to be fixed but for now, you can just edit the Microsoft.Xaml.Behaviors.DesignTools.csproj and change the version from "16.0.0.0" to "16.5.0.0":

![image](https://user-images.githubusercontent.com/85504/91323187-87689c00-e7b8-11ea-8700-ff0c2b64b4fc.png)

**Comment by stevensrf11** [comment]
Oh ok


I update Visual Studio 2019 about once a week.

When I compile any project in VS 2019 I always see something about net core 5 preview message.

The compile error is problem more on the version of Visual Studio 2019 I have installed along with a half million other extensions I have in Visual Studio 2019 like DeveExpress, Reflector, Resharper an so on

 

Thank you for time in responding to message.

My main interest is in looking at the sample behavior code.

Devexpress has wrapped allot of these behaviors and I am looking to see how to duplicate what Devexpress has wrapped, see which ones Devexpress has not wrapped, and also see if there any Devexpress has that source code does not.


 
 

Sent: Wednesday, August 26, 2020 at 10:24 AM
