### ISSUE TITLE
ArgumentException: "EventTrigger" is not a valid type for the TriggerType parameter. Make sure "EventTrigger" derives from TriggerBase

### ISSUE THREAD

**Issue by navin21** [microsoft/XamlBehaviorsWpf#76]
I have plus button in my wpf application when I click that button it opens another tab. Recently we change system.windows.interactivity.dll to Microsoft.Xaml.Behaviors.dll. after this I m getting following error. Any idea how to solve this issue.
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Add value to collection of type 'Microsoft.Xaml.Behaviors.TriggerCollection' threw an exception.' Line number '132' and line position '60'.
  Source=PresentationFramework
Inner Exception 1:
ArgumentException: "EventTrigger" is not a valid type for the TriggerType parameter. Make sure "EventTrigger" derives from TriggerBase.

**Comment by brianlagunas** [comment]
Please provide a sample app that reproduces the problem or this issue will be closed.
