### ISSUE TITLE
KeyTrigger: KeyUp command action is not fired for the modifier keys

### ISSUE THREAD

**Issue by pkulikov** [microsoft/XamlBehaviorsWpf#77]
**Summary**

The following definition **does not** result into the invocation of a command
```xaml
<b:KeyTrigger Key="LeftCtrl" FiredOn="KeyUp">
    <b:InvokeCommandAction Command="..." />
</b:KeyTrigger>
```

(That same behavior is for any modifier key.)

**To reproduce**

- Build and run the following WPF app project (.NET Framework 4.7.2): [KeyTriggerDemo.zip](https://github.com/microsoft/XamlBehaviorsWpf/files/5233743/KeyTriggerDemo.zip)
- Press the LEFT CTRL key several times

**Expected behavior**: Two lines are displayed: "UP UP UP..." and "DOWN DOWN DOWN..."
**Observed behavior**: No "UP"s are displayed.

**Reason**

The root cause is in the *KeyTrigger.cs* file:
https://github.com/microsoft/XamlBehaviorsWpf/blob/7c79fe973777cc261e951bb133dff1974d27cb8a/src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs#L74-L81

When the CTRL key is UP, the `Keyboard.Modifiers` is `None` (at least it has CTRL off), however `GetActualModifiers` returns the instance with CTRL on. Thus, the `if` condition returns `false` and actions are not invoked.

Is that by design or a bug?

**Comment by brianlagunas** [comment]
Please provide a sample application that reproduces the problem or this issue may be closed.

**Comment by pkulikov** [comment]
@brianlagunas I've uploaded the zipped project into the original post. Please check the updated post.

**Comment by montyjohn** [comment]
Has there been any outcome for this issue. It still appears to be a problem.
