### ISSUE TITLE
Migrate to .Net Core 3.1

### ISSUE THREAD

**Issue by alexx-grand** [microsoft/XamlBehaviorsWpf#78]
Hi there!

First of all thanks for the great library!
Is there something blocking you from migrating to .Net Core 3.1?

**Comment by brianlagunas** [comment]
Nope, nothing stopping .NET Core 3.1 support. Would you like to submit a PR?

**Comment by alexx-grand** [comment]
Hi @brianlagunas,

Oh yeah... @punker76 already did it. Thank you
