### ISSUE TITLE
How to resolve NU1202: Package Microsoft.Xaml.Behaviors.Wpf 1.1.19 is not compatible with net50-windows (.NETFramework,Version=v5.0,Profile=windows). Package Microsoft.Xaml.Behaviors.Wpf 1.1.19 supports:

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/XamlBehaviorsWpf#80]
---
**Issue moved from dotnet/sdk#14371**
- Please respond to @mageshsankar.

---

_From @mageshsankar on Thursday, October 29, 2020 12:46:18 PM_

After installing the latest preview, we noticed our WPF apps targeting net50-windows will not compile. We tried to create a new project from scratch and hit the same issue. The simple project file is defined below:

```
<PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```
Cannot restore Microsoft.Xaml.Behaviors.Wpf 1.1.19 package

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#14371**
- Please respond to @Abdullah0820.

---

_From @Abdullah0820 on Thursday, October 29, 2020 7:40:51 PM_

> After installing the latest preview, we noticed our WPF apps targeting net50-windows will not compile. We tried to create a new project from scratch and hit the same issue. The simple project file is defined below:
> 
> 
> 
> ```
> 
> <PropertyGroup>
> 
>     <OutputType>library</OutputType>
> 
>     <TargetFramework>net5.0-windows</TargetFramework>
> 
>     <UseWindowsForms>true</UseWindowsForms>
> 
>     <UseWPF>true</UseWPF>
> 
>     <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
> 
>   </PropertyGroup>
> 
> ```
> 
> Cannot restore Microsoft.Xaml.Behaviors.Wpf 1.1.19 package

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#14371**
- Please respond to @mageshsankar.

---

_From @mageshsankar on Monday, November 9, 2020 4:27:05 AM_

Hi @marcpopMSFT 

Any update on this.

Thanks

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#14371**
- Please respond to @marcpopMSFT.

---

_From @marcpopMSFT on Tuesday, November 10, 2020 7:00:56 PM_

We'll be discussing in triage tomorrow but I suspect that the Behaviors package being referenced needs to be updated to target 5.0

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#14371**
- Please respond to @mageshsankar.

---

_From @mageshsankar on Wednesday, November 11, 2020 9:01:16 AM_

Okay waiting for your suggestion

Thanks

**Comment by marcpopMSFT** [comment]
I checked on NuGet and the version of that binary hasn't been updated since net5.0 released.  To reference it from a net5.0-windows component, it needs to be rebuilt so moving the bug over to them.

**Comment by mgoertz-msft** [comment]
@marcpopMSFT  Correct, targeting net50-windows has not been added to this library yet. Would you like to submit a PR? I would imagine it would need to look similar to PR #79.
