### ISSUE TITLE
Could not load file or assembly Microsoft.Xaml.Behaviors

### ISSUE THREAD

**Issue by quasarea** [microsoft/XamlBehaviorsWpf#86]
**Describe the bug**
Using behaviors in my xaml brings compilation error message. 

**To Reproduce**
```
<Window x:Class="Aveva.SplashScreen.Sample.View.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:b="http://schemas.microsoft.com/xaml/behaviors"
        >
    <b:Interaction.Triggers>
        <b:EventTrigger EventName="MouseDown" >
            <b:InvokeCommandAction 
                Command="{Binding MouseDownCommand}" 
                CommandParameter="{Binding Mode=OneWay, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=Window }}"  />
        </b:EventTrigger>
    </b:Interaction.Triggers>
```

**Error**
```
System.Windows.Markup.XamlParseException: 'Could not load file or assembly 'Microsoft.Xaml.Behaviors, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
```

**Expected behavior**
To work out of the box, without having to reference library in code behind. Because it works fine if I reference anything:
```
        public MainWindow()
        {
            InitializeComponent();
            
            var _ = new Microsoft.Xaml.Behaviors.DefaultTriggerAttribute(typeof(Trigger), typeof(Microsoft.Xaml.Behaviors.TriggerBase), null);
        }
```

**Desktop (please complete the following information):**
 - Version with bug: 1.1.31

**Comment by quasarea** [comment]
Spotted at https://github.com/zspitz/ANTLR4ParseTreeVisualizer/issues/35

**Comment by brianlagunas** [comment]
Please provide a sample that reproduces the issue or this issue will be closed.

**Comment by quasarea** [comment]
Had to be some mess at my side, sorry, could not replicate.

**Comment by Jebarson** [comment]
This  a repro for me. It happens when the Page is in a class library. The easiest workaround is to name behavior command in the xaml.

` <Behaviors:InvokeCommandAction x:Name="SelectionCommand"
                                    Command="{Binding SelectedItemsChangedCommand}"`

**Comment by keparanj** [comment]
Happens for me as well when the WPF project is a class library. Interestingly when I tried to reproduce it in a fresh sample project, I wasn't able to. Perhaps there is something else that is interfering with it. May dig deeper if I get more time

Like @quasarea  mentioned, a quick fix is to simply reference something from within the `Microsoft.Xaml.Behaviors` package before the call to the `Window`'s `InitializeComponent()`

**Comment by LouisCPro** [comment]
Hi,

Same problem with version 1.1.37 of the Microsoft.Xaml.Behaviors Library !

Just added this in the CTOR of the control where I use it: 

`
public MyControl()
        {
            var trig = new Microsoft.Xaml.Behaviors.EventTrigger();
            trig.SourceName = "foo";
            //
            InitializeComponent();
        }
`

And no error after that !

**Comment by jerrud** [comment]
I have the OPs same problem using version 1.1.39. The view is simply a Window in a folder in a class library. The library is a plug-in for another application. Creating a new WPF application and loading in that app as a plugin to the host app does not have this exception. 

I was able to use OPs work around and view now works:
```
        public MainWindow()
        {
            InitializeComponent();
            
            var _ = new Microsoft.Xaml.Behaviors.DefaultTriggerAttribute(typeof(Trigger), typeof(Microsoft.Xaml.Behaviors.TriggerBase), null);
        }
```

**Comment by weitzhandler** [comment]
I have the same issue when trying to add a `ChangePropertyAction` in page located in a referenced class library.
Adding a `x:Name` to the action solved the problem as @Jebarson recommended.

**Comment by Sh3rlck** [comment]
Currently having the same issue. Using it on a class library. 
var _ = new Microsoft.Xaml.Behaviors.DefaultTriggerAttribute(typeof(Trigger), typeof(Microsoft.Xaml.Behaviors.TriggerBase), null);
This does the trick for me as well, wondering is there has been a fix for this or if there is a cleaner way. I will most likely have multiple wpf windows that will requiere access to triggers and I dont want to add this line of code to every single one.

Any help is appreciated.

**Comment by Boorda** [comment]
Same issue, I installed the NuGet pkg and tried to use this interaction logic:
```xml
...
xmlns:b="http://schemas.microsoft.com/xaml/behaviors"
...
```

```xml
...

<Button Content="Button 1">
    <b:Interaction.Triggers>
        <b:EventTrigger EventName="Click">
            <b:InvokeCommandAction Command="{Binding Button1Command}" PassEventArgsToCommand="True" />
        </b:EventTrigger>
    </b:Interaction.Triggers>
</Button>

...
```

**Comment by wegewitzSte** [comment]
Same issue, For a net48 WPF project,

**Comment by HTWeathrt** [comment]
I'm having the same problem as above, it still works but it's quite annoying

<ComboBox ItemsSource="{Binding Machines}"
          SelectedItem="{Binding SelectedMachine}" >
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="DropDownClosed">
            <i:InvokeCommandAction Command="{Binding DropDownClosedCommand}" />
        </i:EventTrigger>
    </i:Interaction.Triggers>
</ComboBox>


Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	XDG0009	Could not load file or assembly 'Microsoft.Xaml.Behaviors, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.	Classification_LGD_V2	C:\Users\Administrator\Documents\Project\Cls_Data\Classification_LGD_NewOJ\classification_lgd\Classification_LGD_V2\Views\Control\Quick_Search\Quick_Search.xaml	31
