### ISSUE TITLE
Allow Task as ReturnType in CallMethodAction

### ISSUE THREAD

**Issue by stevenengland** [microsoft/XamlBehaviorsWpf#87]
**Is your feature request related to a problem? Please describe.**
Binding to Methods is limited to void (void as well as async void is possible). See this example:
```
<b:Interaction.Triggers>
    <b:EventTrigger EventName="PreviewMouseDown">
        <behavior:CustomCallMethodAction MethodName="OnSomeEventThatOccuredAsync"
                            TargetObject="{Binding}" />
    </b:EventTrigger>
</b:Interaction.Triggers>

public async void OnSomeEventThatOccuredAsync(object sender, EventArgs eventArgs){...}
```
It would be nice to be able to handle a Task instead of void.

**Describe the solution you'd like**
In CallMethodAction.cs there is a restriction to void:

```
private bool IsMethodValid(MethodInfo method)
{
    if (!string.Equals(method.Name, this.MethodName, StringComparison.Ordinal))
    {
        return false;
    }

    if (method.ReturnType != typeof(void)) // <-- here
    {
        return false;
    }

    return true;
}
```
Might it be feasable to allow ReturnType Task also? In my simple solution where I wanted it there was no problem when I changed the specific lines to:
```
if (method.ReturnType != typeof(void) && method.ReturnType != typeof(Task))
{
    return false;
}
```
The upcoming calls (especially the invoke() call) worked as expected although I'm not finally sure if there should be a switch to await the task result maybe. I think not but my spare time does not allow a further investigation.

**Describe alternatives you've considered**
Using async void... (!)

**Additional context**
-

**Comment by brianlagunas** [comment]
Thank you for your suggestion. However, this is not something we will be adding.
