### ISSUE TITLE
Release Notes for v1.1.31 

### ISSUE THREAD

**Issue by mark-monteiro** [microsoft/XamlBehaviorsWpf#88]
**Describe the bug**
The latest version released on NuGet is 1.1.31, but there is no associated release or change notes to be found in GitHub or anywhere else as far as I can tell.

**To Reproduce**
N/A

**Expected behavior**
Release notes should be available for the release.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Reproduction Link**
N/A

**Comment by mark-monteiro** [comment]
It would be nice to get an official update on this (and create a tag in the repository/create a release in GitHub). However, for anyone else interested in reviewing the changes manually, these should be the commits included in the 1.1.31 releases: https://github.com/microsoft/XamlBehaviorsWpf/compare/v1.1.19...302a27da21749b330a8b5807bc69f62f4372ff94

Commit 302a27da21749b330a8b5807bc69f62f4372ff94 is from Jan 4, 2021, which is the same date 1.1.31 was released on NuGet and should be the last commit that *could have* been included in the release.

**Comment by lightwalker01** [comment]
Now latest release is 1.1.37 and tags&releases are stuck to 1.1.19.
How to know the change list?

**Comment by DVaughan** [comment]
There have been no functional changes. Only fixes to the Authenticode signing of assemblies within the NuGet package.

**Comment by lightwalker01** [comment]
> There have been no functional changes. Only fixes to the Authenticode signing of assemblies within the NuGet package.

Ok, thanks @DVaughan

**Comment by brianlagunas** [comment]
Release notes are here https://github.com/microsoft/XamlBehaviorsWpf/releases/tag/v1.1.31
