### ISSUE TITLE
Strong name validation failed loading the design time assembly

### ISSUE THREAD

**Issue by 536b6f74746b69** [microsoft/XamlBehaviorsWpf#89]
**Describe the bug**
General output shows exception message when using XamlBehaviorsWpf. 
Designer and Program do work as intended.

**To Reproduce**
1.Load Solution/Project containing reference on Microsoft.Xaml.Behaviors.Wpf
2. Open Output->General
3. See error
```
There was an exception when loading the design time assembly 
C:\Users\%USERNAME%\AppData\Local\Microsoft\VisualStudio\16.0_c41b5f41\Designer\ShadowCache\o23at5zu.4ir\bc0jsohr.34f\Design\Microsoft.Xaml.Behaviors.Design.dll':`
Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Expected behavior**
No error

**Screenshots**
![Error_StrongNameValidation](https://user-images.githubusercontent.com/80458756/110781708-8683ed00-8266-11eb-9396-c43c69b3a9c6.jpg)

**Desktop (please complete the following information):**
- Windows: Windows 10 Enterprise v1809
- Microsoft Visual Studio Professional 2019
  Version 16.9.0
  VisualStudio.16.Release/16.9.0+31025.194
  Microsoft .NET Framework
  Version 4.8.03761
 - Target Framework: .NET Framework 4.5.2
 - Version with bug: 1.1.31
 - Last known working version: /

**Reproduction Link**
[XamlBehavioursExample.zip](https://github.com/microsoft/XamlBehaviorsWpf/files/6122694/XamlBehavioursExample.zip)

**Comment by jstevenson72** [comment]
Any movement on this?  Just started having this issue in latest Visual Studio 2019 / .Net 4.8

**Comment by msedi** [comment]
I have the same problem with .NET 6 Preview 7 and earlier. If I uninstall it works again.
Interestingly if I create a simple project everything works, but if I check with larger projects it shows the error.
One hint that might help: What I saw is when I'm using Directory.Build.props in a cascaded way that it's obviously causing the problem.
