### ISSUE TITLE
[Blend]Unable to set TargetName property in the properties panel for ChangePropertyAction

### ISSUE THREAD

**Issue by v-nidu** [microsoft/XamlBehaviorsWpf#90]
**Describe the bug**
[Blend]Unable to set TargetName property in the properties panel for ChangePropertyAction

**To Reproduce**
1.  Open Blend.
2.  Create a wpf(.NetCore) project
3.  Add a button to the design surface so that you have something for the  Behaviors to interact with.
4.  In the Assets pane, go to Behaviors and click the “Install ‘Behaviors’ NuGet  Package” link.
5.  Several new behaviors will show up in the Behaviors tab of the Assets pane.  Drag a ChangePropertyAction behavior to Button on the design surface and the  Xaml for that behavior will be auto-generated. 

**Expected behavior**
We can set TargetName property in the properties panel for  ChangePropertyAction

**Actual behavior**
Unable to set TargetName property in the properties panel for  ChangePropertyAction

**Screenshots**
![attachments](https://user-images.githubusercontent.com/56945713/113801018-966dee80-978a-11eb-96e5-82dcfc592f91.gif)

**Desktop (please complete the following information):**
Affected Branch: main
Affected Build: 31002.210
Affected Product Language: ENT

**Comment by yariker** [comment]
Any update on this issue? I would consider it a major one. Still reproducible in Blend 2022, version 17.2.2.

This literally makes Blend useless in creating/editing any interactivity via the designer, which was the whole point of Blend initially.

**Comment by yariker** [comment]
@mgoertz-msft got it, thanks. I have reported it here: https://developercommunity.visualstudio.com/t/Cannot-to-set-some-of-the-WPF-ActionBeh/10053607

**Comment by brianlagunas** [comment]
Closing this as it has been reported to Visual Studio team
