### ISSUE TITLE
EventTriggers not removed on Unloaded

### ISSUE THREAD

**Issue by Nils-Berghs** [microsoft/XamlBehaviorsWpf#93]
Consider a user control on which behaviors are attached as 

```
<behaviors:Interaction.Triggers>
        <behaviors:KeyTrigger Key="NumPad0" FiredOn="KeyDown">
            <behaviors:InvokeCommandAction Command="{Binding OnKeyPressedCommand}" 
                 PassEventArgsToCommand="True"/>
        </behaviors:KeyTrigger>
</behaviors:Interaction.Triggers>
```
When such a user control gets unloaded an loaded again the commands are executed twice (and an extra time for each next unload/load combination).

Somehow the triggers are not removed after unloading, and I cannot seem to find a way to access them from code behind of the usercontrol.

**Comment by Nils-Berghs** [comment]
After some digging in the code I have found that the Loaded event on the user control is handled by the `EventTriggerBase` and causes an OnEvent in the `KeyTrigger`, which added event listener for key up / down.

There is however no handling for an unloaded event. A quick fix is to change the OnEvent in the KeyTrigger and remove the events prior to adding them, thus avoiding duplicates. I will create a pull request.

**Comment by brianlagunas** [comment]
Do you have a sample to share that demonstrates the issue?

**Comment by Nils-Berghs** [comment]
Ok, I'm not sure I follow your reasoning completely. The Ke event handlers are added to the MainWindow on the load of the usercontrol, I don't see why they cannot be removed on the unload of the usercontrol. There might be situations where you want them to remain, although in such case they could be added to the window itself.

That being said, the workaround is acceptable to me, and clearing the triggers was the first thing I tried, but I didn't found out how. The proposed workaround is simple and works.

**Comment by brianlagunas** [comment]
To close out this thread, I have tested the suggested approach to try and fix this, but it is not possible without making other high risk changes.  

See this comment for more info https://github.com/microsoft/XamlBehaviorsWpf/pull/97#issuecomment-949197229

You will need to make sure you are removing your behaviors manually.
