### ISSUE TITLE
Unable to install Visual Studio 2012

### ISSUE THREAD

**Issue by AndrewDavid007** [microsoft/XamlBehaviorsWpf#99]
Install-Package : Unable to load the service index for source https://packagesource.
  An error occurred while sending the request.
  The remote name could not be resolved: 'packagesource'
At line:1 char:1
+ Install-Package Microsoft.Xaml.Behaviors.Wpf -Version 1.1.39
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**To Reproduce**
1. Go to NuGet Package Manager
2. Click on Install
3. See error

**Expected behavior**
Install

**Screenshots**
Severity	Code	Description	Project	File	Line	Suppression State Error
Exception 'System.AggregateException' thrown when trying to add source 'https://packagesource'. Please verify all your online package sources are available. One or more errors occurred. Unable to load the service index for source https://packagesource.
An error occurred while sending the request. The remote name could not be resolved: 'packagesource'				

**Desktop (please complete the following information):**
 - Version with bug: 1.1.39
 - Last known working version: N/A

**Reproduction Link**
![image](https://user-images.githubusercontent.com/28820424/143377835-facbdba8-201e-4e77-92c0-ac861f652aa8.png)

**Comment by brianlagunas** [comment]
Unable to duplicate. You should double check your package sources and make sure they are all valid.
